// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM5JxfOqEEQ3Nm0mTrOSVVfq9g_tpsKKk',
    appId: '1:131047685591:web:2e09e85da648891bdd5f92',
    messagingSenderId: '131047685591',
    projectId: 'thruthbridge',
    authDomain: 'thruthbridge.firebaseapp.com',
    databaseURL: 'https://thruthbridge-default-rtdb.firebaseio.com',
    storageBucket: 'thruthbridge.appspot.com',
    measurementId: 'G-5ME7WB853K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiCtr3CySK2cI7fPlCiTH04uSg92KZfnc',
    appId: '1:131047685591:android:14964ae5e6bdd2e5dd5f92',
    messagingSenderId: '131047685591',
    projectId: 'thruthbridge',
    databaseURL: 'https://thruthbridge-default-rtdb.firebaseio.com',
    storageBucket: 'thruthbridge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQMxDx0dEfAYuldeLOWiJj0lZYJf2txwM',
    appId: '1:131047685591:ios:edb05aaf78a0f3ebdd5f92',
    messagingSenderId: '131047685591',
    projectId: 'thruthbridge',
    databaseURL: 'https://thruthbridge-default-rtdb.firebaseio.com',
    storageBucket: 'thruthbridge.appspot.com',
    iosClientId: '131047685591-tlmthlp4pl3nrsgae1rf58tfdpkpmdin.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQMxDx0dEfAYuldeLOWiJj0lZYJf2txwM',
    appId: '1:131047685591:ios:edb05aaf78a0f3ebdd5f92',
    messagingSenderId: '131047685591',
    projectId: 'thruthbridge',
    databaseURL: 'https://thruthbridge-default-rtdb.firebaseio.com',
    storageBucket: 'thruthbridge.appspot.com',
    iosClientId: '131047685591-tlmthlp4pl3nrsgae1rf58tfdpkpmdin.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM5JxfOqEEQ3Nm0mTrOSVVfq9g_tpsKKk',
    appId: '1:131047685591:web:c16bf982cfbb53a1dd5f92',
    messagingSenderId: '131047685591',
    projectId: 'thruthbridge',
    authDomain: 'thruthbridge.firebaseapp.com',
    databaseURL: 'https://thruthbridge-default-rtdb.firebaseio.com',
    storageBucket: 'thruthbridge.appspot.com',
    measurementId: 'G-FZK2E6V8W4',
  );
}